//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feriados
    {
        public int cd_consorcio { get; set; }
        public int cd_fecha { get; set; }
        public System.DateTime fc_fecha { get; set; }
        public string tx_descripcion { get; set; }
    
        public virtual Consorcio Consorcio { get; set; }
    }
}
