//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Sum1Entities : DbContext
    {
        public Sum1Entities()
            : base("name=Sum1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consorcio> Consorcio { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Espacio> Espacio { get; set; }
        public virtual DbSet<Feriados> Feriados { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Reclamo> Reclamo { get; set; }
        public virtual DbSet<Reserva> Reserva { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<sp_GastosMensuales_Result> sp_GastosMensuales(Nullable<System.DateTime> mesano, Nullable<int> consorcio)
        {
            var mesanoParameter = mesano.HasValue ?
                new ObjectParameter("mesano", mesano) :
                new ObjectParameter("mesano", typeof(System.DateTime));
    
            var consorcioParameter = consorcio.HasValue ?
                new ObjectParameter("consorcio", consorcio) :
                new ObjectParameter("consorcio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GastosMensuales_Result>("sp_GastosMensuales", mesanoParameter, consorcioParameter);
        }
    
        public virtual ObjectResult<sp_GastosMensualesDetalle_Result> sp_GastosMensualesDetalle(Nullable<System.DateTime> mesano, Nullable<int> consorcio, string usuario)
        {
            var mesanoParameter = mesano.HasValue ?
                new ObjectParameter("mesano", mesano) :
                new ObjectParameter("mesano", typeof(System.DateTime));
    
            var consorcioParameter = consorcio.HasValue ?
                new ObjectParameter("consorcio", consorcio) :
                new ObjectParameter("consorcio", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GastosMensualesDetalle_Result>("sp_GastosMensualesDetalle", mesanoParameter, consorcioParameter, usuarioParameter);
        }
    }
}
