//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamo
    {
        public int cd_consorcio { get; set; }
        public int cd_reclamo { get; set; }
        public string cd_usuario { get; set; }
        public string tx_reclamo { get; set; }
        public bool fl_publico { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
