//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int cd_consorcio { get; set; }
        public int cd_espacio { get; set; }
        public string cd_usuario { get; set; }
        public System.DateTime fc_fecha { get; set; }
        public bool fl_contrata_limpieza { get; set; }
        public bool fl_multa { get; set; }
        public string tx_observacion { get; set; }
    
        public virtual Espacio Espacio { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
